### ISSUE TITLE
EACCES on tmp/memstore.sock

### ISSUE THREAD

**Issue by artis3n** [coolaj86/memstore-cluster#2]
After setting up the store as specified in the documentation, I'm getting the following error. I wonder if I have set up the cluster store correctly (in which case, this issue can be improving the documentation), or if there is an issue with the library that calls this EACCES error.

```
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: listen EACCES ./tmp/memstore.sock
    at Object.exports._errnoException (util.js:856:11)
    at exports._exceptionWithHostPort (util.js:879:20)
    at Server._listen2 (net.js:1221:19)
    at listen (net.js:1270:10)
    at Server.listen (net.js:1360:5)
    at /home/akalfus/Copy/Development/Schedule/node_modules/cluster-store/server.js:136:14
    at FSReqWrap.oncomplete (fs.js:82:15)
```

My cluster store is set up as:

```
const cstore = require('cluster-store');
const sessOptions = {
  sock: './tmp/memstore.sock',

  // If left 'null' or 'undefined' this defaults to a similar memstore
  // with no special logic for 'cookie' or 'expires'
  store: cluster.isMaster && new require('express-session/session/memory')(),

  // Good default to use for instances where you might want
  // to cluster or to run standalone, but with same API
  serve: cluster.isMaster,
  connect: cluster.isWorker,
  standalone: (numCPUs === 1) // override serve and connect
};
```

Then, the store is set as such:

```
app.use(session({
    secret: params.cookieSecret,
    name: 'LTSHD.sid',
    resave: false,
    saveUninitialized: false,
    cookie: { secure: true, httpOnly: true },
    store: cstore
  }));
```

**Comment by coolaj86** [comment]
Should be `/tmp/memstore.sock` or `./memstore.sock`, but not `./tmp/memstore.sock`

**Comment by artis3n** [comment]
Thanks, my mistake!
